name: PHPUnit tests

on:
    - push
    - pull_request

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [7.4, 8.0, 8.2, 8.2, 8.3]
                laravel: [7.*, 8.*, 9.*, 10.*, 11.*]
                exclude:
                    - laravel: 7.*
                      php: 8.1
                    - laravel: 7.*
                      php: 8.2
                    - laravel: 7.*
                      php: 8.3
                    - laravel: 8.*
                      php: 8.2
                    - laravel: 8.*
                      php: 8.3
                    - laravel: 9.*
                      php: 7.4
                    - laravel: 10.*
                      php: 7.4
                    - laravel: 10.*
                      php: 8.0
                    - laravel: 11.*
                      php: 7.4
                    - laravel: 11.*
                      php: 8.0
                    - laravel: 11.*
                      php: 8.1

        name: Tests on PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --dev --no-interaction --no-update
                  composer update --prefer-source --no-interaction --no-progress

            - name: Execute tests
              run: vendor/bin/phpunit --verbose
